# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-26 10:51
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0007_auto_20170925_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitbitActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(30)])),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Date')),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
