# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-27 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_fitbitactivities'),
        ('exercises', '0008_remove_exercise_user'),
    ]

    operations = [
    ]
